// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/telegram_id.proto

package casterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelegramIdStore struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelegramIdStore) Reset() {
	*x = TelegramIdStore{}
	mi := &file_proto_telegram_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramIdStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramIdStore) ProtoMessage() {}

func (x *TelegramIdStore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telegram_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramIdStore.ProtoReflect.Descriptor instead.
func (*TelegramIdStore) Descriptor() ([]byte, []int) {
	return file_proto_telegram_id_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramIdStore) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TelegramIdStore) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

var File_proto_telegram_id_proto protoreflect.FileDescriptor

const file_proto_telegram_id_proto_rawDesc = "" +
	"\n" +
	"\x17proto/telegram_id.proto\x12\x06caster\"X\n" +
	"\x0fTelegramIdStore\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayloadB\x1fZ\x1dmurmapp.caster/proto;casterpbb\x06proto3"

var (
	file_proto_telegram_id_proto_rawDescOnce sync.Once
	file_proto_telegram_id_proto_rawDescData []byte
)

func file_proto_telegram_id_proto_rawDescGZIP() []byte {
	file_proto_telegram_id_proto_rawDescOnce.Do(func() {
		file_proto_telegram_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telegram_id_proto_rawDesc), len(file_proto_telegram_id_proto_rawDesc)))
	})
	return file_proto_telegram_id_proto_rawDescData
}

var file_proto_telegram_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_telegram_id_proto_goTypes = []any{
	(*TelegramIdStore)(nil), // 0: caster.TelegramIdStore
}
var file_proto_telegram_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_telegram_id_proto_init() }
func file_proto_telegram_id_proto_init() {
	if File_proto_telegram_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telegram_id_proto_rawDesc), len(file_proto_telegram_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_telegram_id_proto_goTypes,
		DependencyIndexes: file_proto_telegram_id_proto_depIdxs,
		MessageInfos:      file_proto_telegram_id_proto_msgTypes,
	}.Build()
	File_proto_telegram_id_proto = out.File
	file_proto_telegram_id_proto_goTypes = nil
	file_proto_telegram_id_proto_depIdxs = nil
}
