name: Deploy murmapp.caster

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      SECRET_SALT: ${{ secrets.SECRET_SALT }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      BOT_ENCRYPTION_KEY: ${{ secrets.BOT_ENCRYPTION_KEY }}
      TELEGRAM_ID_ENCRYPTION_KEY: ${{ secrets.TELEGRAM_ID_ENCRYPTION_KEY }}
      WEB_HOOK_HOST: ${{ secrets.WEB_HOOK_HOST }}
      APP_PORT: ${{ secrets.APP_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build binary
        run: go build -o app ./cmd/main.go

      - name: Upload binary to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: "app"
          target: "~/murmapp/murmapp.caster"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          envs: SECRET_SALT,TELEGRAM_API_URL,RABBITMQ_URL,WEB_HOOK_HOST,APP_PORT,BOT_ENCRYPTION_KEY,TELEGRAM_ID_ENCRYPTION_KEY,ENCRYPTION_KEY
          script: |
            cd ~/murmapp/murmapp.caster

            cat <<EOF > .env
            SECRET_SALT=$SECRET_SALT
            TELEGRAM_API_URL=$TELEGRAM_API_URL
            BOT_ENCRYPTION_KEY=$BOT_ENCRYPTION_KEY
            ENCRYPTION_KEY=$ENCRYPTION_KEY
            TELEGRAM_ID_ENCRYPTION_KEY=$TELEGRAM_ID_ENCRYPTION_KEY
            RABBITMQ_URL=$RABBITMQ_URL
            WEB_HOOK_HOST=$WEB_HOOK_HOST
            APP_PORT=$APP_PORT
            EOF

            sudo systemctl restart murmapp-caster.service
