name: Deploy murmapp.caster

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      APP_PORT: ${{ secrets.APP_PORT }}
      TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
      WEB_HOOK_HOST: ${{ secrets.WEB_HOOK_HOST }}
      RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
      SECRET_SALT: ${{ secrets.SECRET_SALT }}
      PAYLOAD_ENCRYPTION_KEY: ${{ secrets.PAYLOAD_ENCRYPTION_KEY }}
      ENCRYPTED_PRIVATE_KEY: ${{ secrets.ENCRYPTED_PRIVATE_KEY }}
      PUBLIC_KEY_RAW_BASE64: ${{ secrets.PUBLIC_KEY_RAW_BASE64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
      - name: Create go.work
        run: |
          echo 'go 1.24.1\n\nuse ./' > go.work

      - name: Build binary
        run: |
          go mod tidy
          go build -ldflags "-X=murmappcaster/internal/config.MasterEncryptionKey=${{ secrets.MASTER_SECRET_KEY }}" \
          -o app ./cmd/main.go
      - name: Upload binary to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: "app"
          target: "~/murmapp/murmapp.caster"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          envs: APP_PORT,WEB_HOOK_HOST,TELEGRAM_API_URL,RABBITMQ_URL,REDIS_URL,POSTGRES_DSN,SECRET_SALT,PAYLOAD_ENCRYPTION_KEY,ENCRYPTED_PRIVATE_KEY,PUBLIC_KEY_RAW_BASE64
          script: |
            set -eu
            cd ~/murmapp/murmapp.caster

            cat <<EOF > .env
            APP_PORT=$APP_PORT
            TELEGRAM_API_URL=$TELEGRAM_API_URL
            WEB_HOOK_HOST=$WEB_HOOK_HOST
            RABBITMQ_URL=$RABBITMQ_URL
            REDIS_URL=$REDIS_URL
            POSTGRES_DSN=$POSTGRES_DSN
            PAYLOAD_ENCRYPTION_KEY=$PAYLOAD_ENCRYPTION_KEY
            SECRET_SALT=$SECRET_SALT
            ENCRYPTED_PRIVATE_KEY=$ENCRYPTED_PRIVATE_KEY
            PUBLIC_KEY_RAW_BASE64=$PUBLIC_KEY_RAW_BASE64
            EOF

            sudo systemctl restart murmapp-caster.service
